### ISSUE TITLE
Not working web_1

### ISSUE THREAD

**Issue by vladimirlukyanov** [pm-str/QuestBot#3]
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1     |     return self.cursor.execute(sql, params)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
web_1     |     return Database.Cursor.execute(self, query, params)
web_1     | sqlite3.OperationalError: no such table: main.web_step__old
web_1     |
web_1     | The above exception was the direct cause of the following exception:
web_1     |
web_1     | Traceback (most recent call last):
web_1     |   File "./su_setup.py", line 16, in <module>
web_1     |     User.objects.create_superuser(username=username, email=email, password=password)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 161, in create_superuser
web_1     |     return self._create_user(username, email, password, **extra_fields)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 144, in _create_user
web_1     |     user.save(using=self._db)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
web_1     |     super().save(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
web_1     |     force_update=force_update, update_fields=update_fields)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
web_1     |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
web_1     |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
web_1     |     using=using, raw=raw)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1     |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
web_1     |     return query.get_compiler(using=using).execute_sql(return_id)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1280, in execute_sql
web_1     |     cursor.execute(sql, params)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
web_1     |     return super().execute(sql, params)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
web_1     |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
web_1     |     return executor(sql, params, many, context)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1     |     return self.cursor.execute(sql, params)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
web_1     |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1     |     return self.cursor.execute(sql, params)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
web_1     |     return Database.Cursor.execute(self, query, params)
web_1     | django.db.utils.OperationalError: no such table: main.web_step__old

**Comment by Doncode** [comment]
Проблема в работе  Django c sqllite 
https://stackoverflow.com/questions/53637182/django-no-such-table-main-auth-user-old
